"""
thesis_render.py
================
Turns the assembled case from thesis_page into one readable page.

Kept separate from the analysis so the argument and its presentation can be
changed independently — and so a rendering bug can never be mistaken for a
change in the evidence.

DESIGN NOTES
------------
The page is a CASE FILE, not a dashboard, and it is built to be read top to
bottom: verdict, clock, ledger, expression, falsifiers. The FOR and AGAINST
columns are deliberately the same width and weight. On this universe the base
rate is 13% and implied volatility runs richer than realized, so most honest
verdicts are NO TRADE; a layout that made the bull case bigger than the bear
case would be arguing for a position the data does not support.

Colours come from the analyzer's own palette so the page reads as part of the
toolkit rather than a export from somewhere else. It commits to a single dark
theme on purpose — it is generated by a dark application and opened beside it.
"""

import html
import json
import os
import webbrowser
from datetime import date, datetime

_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(_DIR, "thesis")


def _f(v, default=None):
    try:
        x = float(v)
        return x if x == x else default
    except (TypeError, ValueError):
        return default


def _g(obj, name, default=None):
    v = getattr(obj, name, default) if obj is not None else default
    return default if v is None else v


def _pct(v, digits=0, blank="—"):
    x = _f(v)
    return blank if x is None else f"{x:.{digits}%}"


def _num(v, digits=1, blank="—"):
    x = _f(v)
    return blank if x is None else f"{x:,.{digits}f}"


def _esc(s):
    return html.escape(str(s if s is not None else ""))


CSS = """
:root{
  --ground:#0A0E14; --surface:#12171F; --line:#252C3B;
  --text:#CDD6F4; --dim:#8B92A8; --faint:#646B80;
  --accent:#F4C430; --for:#A6E3A1; --against:#F38BA8;
  --cool:#94E2D5; --info:#89B4FA;
}
*{box-sizing:border-box}
html,body{margin:0;padding:0}
body{background:var(--ground);color:var(--text);
  font-family:"Newsreader",Georgia,serif;font-size:16px;line-height:1.6;
  -webkit-font-smoothing:antialiased;}
.wrap{max-width:1120px;margin:0 auto;padding:0 26px 80px}
h1,h2,.lab,.verdict,th,.item .k{font-family:"Archivo",Helvetica,Arial,sans-serif}
.lab{font-size:.7rem;letter-spacing:.16em;text-transform:uppercase;
  color:var(--faint);font-weight:600;margin:0 0 10px}
header.hero{padding:40px 0 26px;border-bottom:1px solid var(--line)}
.tick{display:flex;align-items:baseline;gap:16px;flex-wrap:wrap}
.tick h1{font-size:2.6rem;font-weight:700;letter-spacing:-.02em;margin:0}
.tick .px{font-family:"JetBrains Mono",ui-monospace,monospace;font-size:1.15rem;
  color:var(--dim);font-variant-numeric:tabular-nums}
.verdict{display:inline-block;margin:18px 0 12px;padding:10px 22px;
  font-size:1.5rem;font-weight:700;letter-spacing:.04em;border-radius:3px}
.v-no{background:var(--against);color:#1A0910}
.v-go{background:var(--for);color:#08170D}
.v-wait{background:var(--accent);color:#1A1400}
.why{max-width:66ch;margin:0}
section{padding:34px 0;border-bottom:1px solid var(--line)}
h2{font-size:1.3rem;font-weight:700;margin:0 0 4px}
.sub{color:var(--dim);font-size:.94rem;max-width:72ch;margin:0 0 18px}
.clock{margin:22px 0 4px;overflow-x:auto}
.axis{position:relative;height:150px;min-width:620px;
  border-left:1px solid var(--line)}
.rail{position:absolute;left:0;right:0;top:62px;height:2px;background:var(--line)}
.mark{position:absolute;top:0;transform:translateX(-50%);text-align:center;
  font-size:.68rem;width:150px;
  font-family:"JetBrains Mono",ui-monospace,monospace}
.mark .stem{width:2px;height:44px;margin:5px auto 0}
.mark.catalyst{color:var(--against)}
.mark.catalyst .stem{background:var(--against)}
.mark.earnings{color:var(--accent)}
.mark.earnings .stem{background:var(--accent)}
.exp{position:absolute;top:72px;transform:translateX(-50%);text-align:center;
  font-size:.62rem;color:var(--dim);width:78px;
  font-family:"JetBrains Mono",ui-monospace,monospace}
.exp .dot{width:9px;height:9px;border-radius:50%;margin:0 auto 6px;
  background:var(--info);border:2px solid var(--ground)}
.exp.miss .dot{background:var(--against)}
.exp.cover .dot{background:var(--for)}
.today{position:absolute;left:2px;top:44px;font-size:.66rem;color:var(--cool);
  font-family:"JetBrains Mono",ui-monospace,monospace}
.ledger{display:grid;grid-template-columns:1fr 1fr;gap:22px}
@media(max-width:820px){.ledger{grid-template-columns:1fr}}
.col{background:var(--surface);border:1px solid var(--line);border-radius:4px;
  padding:18px 22px}
.col.for{border-top:2px solid var(--for)}
.col.against{border-top:2px solid var(--against)}
.col.unknown{border-top:2px solid var(--faint)}
.item{padding:12px 0;border-bottom:1px solid var(--line)}
.item:last-child{border-bottom:none}
.item .k{font-size:.7rem;letter-spacing:.1em;text-transform:uppercase;
  color:var(--faint);font-weight:600}
.item .v{font-family:"JetBrains Mono",ui-monospace,monospace;font-size:1.05rem;
  margin:3px 0 5px;font-variant-numeric:tabular-nums}
.item .d{font-size:.86rem;color:var(--dim);line-height:1.5}
.col.for .v{color:var(--for)}
.col.against .v{color:var(--against)}
.tbl{overflow-x:auto;border:1px solid var(--line);border-radius:4px;
  background:var(--surface)}
table{border-collapse:collapse;width:100%;min-width:620px;font-size:.85rem}
th{text-align:left;font-size:.65rem;letter-spacing:.12em;text-transform:uppercase;
  color:var(--faint);padding:11px 14px;border-bottom:1px solid var(--line);
  white-space:nowrap;font-weight:600}
td{padding:10px 14px;border-bottom:1px solid var(--line);
  font-family:"JetBrains Mono",ui-monospace,monospace;
  font-variant-numeric:tabular-nums}
tr:last-child td{border-bottom:none}
td.name{font-family:"Newsreader",Georgia,serif;font-variant-numeric:normal}
.pos{color:var(--for)}
.neg{color:var(--against)}
ul.fals{margin:0;padding-left:20px;max-width:74ch}
ul.fals li{margin-bottom:11px}
footer{padding:30px 0 0;font-family:"JetBrains Mono",ui-monospace,monospace;
  font-size:.72rem;color:var(--faint);line-height:1.75}
@media(prefers-reduced-motion:reduce){*{animation:none!important;
  transition:none!important}}
"""


def _clock_html(clock):
    marks = "".join(
        '<div class="mark {k}" style="left:{p:.2f}%"><div>{l}</div>'
        '<div>{d:%b %d}</div><div class="stem"></div></div>'.format(
            k=m["kind"], p=m["pct"] * 100, l=_esc(m["label"]), d=m["date"])
        for m in clock["marks"])
    exps = "".join(
        '<div class="exp {c}" style="left:{p:.2f}%"><div class="dot"></div>'
        '{d:%m-%d}<br>{n}d</div>'.format(
            c=("miss" if e["misses"] else ("cover" if e["covers"] else "")),
            p=e["pct"] * 100, d=e["date"], n=e["days"])
        for e in clock["expiries"])
    return ('<div class="clock"><div class="axis">'
            '<div class="today">TODAY {t:%b %d}</div>'
            '<div class="rail"></div>{m}{e}</div></div>').format(
        t=clock["today"], m=marks, e=exps)


def _items_html(items, cls):
    title = {"for": "The case for", "against": "The case against",
             "unknown": "Present but unweighted"}[cls]
    if not items:
        return ('<div class="col {c}"><p class="lab">{t}</p>'
                '<div class="item"><div class="d">Nothing recorded.</div>'
                '</div></div>').format(c=cls, t=title)
    rows = "".join(
        '<div class="item"><div class="k">{k}</div><div class="v">{v}</div>'
        '<div class="d">{d}</div></div>'.format(k=_esc(k), v=_esc(v), d=_esc(d))
        for k, v, d in items)
    return '<div class="col {c}"><p class="lab">{t}</p>{r}</div>'.format(
        c=cls, t=title, r=rows)


def _cfg():
    try:
        import trading_config
        return trading_config.load()
    except Exception:
        return {"capital": 0.0, "max_position_pct": 0.0}


def _structures_html(opt):
    st = (opt or {}).get("structures") or {}
    if not st:
        return ('<p class="sub">No structure survived the liquidity and cost '
                'filters. Outside market hours every bid is cleared, and a '
                'spread cannot be priced without a bid to sell into.</p>')
    rows = ""
    for k, r in sorted(st.items(), key=lambda kv: -(kv[1].get("kelly") or -9)):
        ev, kel = _f(r.get("ev")), _f(r.get("kelly"))
        sz = r.get("sizing") or {}
        n_ct = sz.get("contracts", 0)
        if n_ct >= 1:
            order = ('<span class="pos">{}×</span> = ${:,.0f} ({:.0%})'
                     .format(n_ct, sz["dollars"], sz["pct"]))
        else:
            order = ('<span class="neg">—</span> <span style="opacity:.7">{}'
                     '</span>'.format(_esc(sz.get("bound_by", "not sized"))))
        rows += ('<tr><td class="name">{k}</td><td class="name">{n}</td>'
                 '<td>{deb}</td><td>{pc}</td><td class="{ec}">{ev}</td>'
                 '<td class="{kc}">{kel}</td><td>{pw}</td>'
                 '<td class="name">{o}</td></tr>').format(
            k=_esc(k), n=_esc(r.get("name", "")), deb=_num(r.get("debit"), 2),
            pc="${:,.0f}".format(sz.get("per_contract", 0)),
            ec="pos" if (ev or 0) > 0 else "neg", ev=_pct(ev),
            kc="pos" if (kel or 0) > 0 else "neg", kel=_num(kel, 2),
            pw=_pct(r.get("p_profit")), o=order)
    return ('<div class="tbl"><table><thead><tr><th>family</th>'
            '<th>structure</th><th>debit</th><th>per contract</th><th>EV</th>'
            '<th>Kelly</th><th>P(win)</th><th>your order</th>'
            '</tr></thead><tbody>' + rows + '</tbody></table></div>')


def _falsifiers(case, opt):
    out = []
    lp = case["learned"]
    vp = lp.get("vol_premium") or {}
    ratio, im = _f(vp.get("ratio")), case.get("implied_move")
    if ratio and im:
        out.append("Implied move falls below <b>{:.1%}</b>, or your thesis "
                   "rises above it. Today the market charges {:.1%} for "
                   "movement these names have delivered {:.2f}× of."
                   .format(im * ratio, im, ratio))
    fam = case.get("family")
    vs = ((lp.get("verdicts") or {}).get("families") or {}).get(fam)
    if vs and vs["mean_10d"] <= -3.0:
        out.append("The verdict moves off <b>{}</b>. That family averages "
                   "{:+.1f}% over {} graded episodes; BUILDING has been the "
                   "only family with a positive mean."
                   .format(_esc(fam), vs["mean_10d"], vs["n"]))
    cal = lp.get("calibration") or {}
    if not cal.get("active"):
        out.append("The calibration model clears its gate (holdout AUC "
                   "≥0.55). Until it does there is no per-candidate "
                   "probability, and every number here is a base rate plus "
                   "your own scenario.")
    if not (opt or {}).get("structures"):
        out.append("A live session provides two-sided quotes so a spread can "
                   "be priced. A long call buys the volatility premium; a "
                   "spread sells part of it back.")
    out.append("A filled trade lands in the journal. With no closed trades "
               "there is no realized evidence that any of this prices "
               "correctly — only that it is internally consistent.")
    return "".join("<li>{}</li>".format(s) for s in out)


def render(ticker, case, clock, opt=None, out_path="", open_after=True):
    lp = case["learned"]
    cal = lp.get("calibration") or {}
    ps = lp.get("path_shape_event") or {}
    vcls = {"NO TRADE": "v-no", "TRADEABLE": "v-go",
            "WAIT": "v-wait"}.get(case["verdict"], "v-wait")
    spot = case["spot"]
    unknown_block = ""
    if case["unknown"]:
        unknown_block = ('<div class="ledger" style="margin-top:22px">'
                         + _items_html(case["unknown"], "unknown") + "</div>")

    doc = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{tk} Squeeze Thesis</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@600;700&amp;family=JetBrains+Mono:wght@400;500&amp;family=Newsreader:opsz,wght@6..72,400;6..72,500&amp;display=swap">
<style>{css}</style></head><body><div class="wrap">

<header class="hero">
  <p class="lab">Squeeze thesis &middot; generated {now:%d %b %Y %H:%M}</p>
  <div class="tick"><h1>{tk}</h1><span class="px">{px}</span>
    <span class="px">{dv}</span></div>
  <div class="verdict {vcls}">{verdict}</div>
  <p class="why">{why}</p>
</header>

<section>
  <h2>The clock</h2>
  <p class="sub">Every date that matters on one axis. A green dot marks an
  expiry that covers the events; red misses at least one. An expiry can cover
  the close-out and still expire before earnings, and that gap is invisible on
  every other screen.</p>
  {clock}
</section>

<section>
  <div class="ledger">{forc}{against}</div>
  {unknown}
</section>

<section>
  <h2>The expression</h2>
  <p class="sub">Best structure of each family, all scored on one
  distribution, one forward, one crush assumption and full round-trip costs.
  <b>Your order</b> is quarter-Kelly against {cap}, capped at
  {maxpct} — structures whose single contract exceeds that ceiling are
  dropped entirely, because an idea you cannot buy is not a trade.</p>
  {structures}
</section>

<section>
  <h2>What would change this</h2>
  <p class="sub">The conditions under which the verdict flips. A verdict you
  cannot argue with is a verdict you cannot learn from.</p>
  <ul class="fals">{falsifiers}</ul>
</section>

<footer>
  <div>EVIDENCE BASE — calibration n={cn} ({cw}W/{cl}L) across {ceff}
  independent episodes after collapsing repeat scans of the same ticker;
  path shape from {pn} event-aligned episodes; volatility premium from
  {vn} episodes.</div>
  <div style="margin-top:10px">Quotes are delayed and may be prior-session.
  This page ranks structures and states a verdict under disclosed
  assumptions. It does not know your position size, your alternatives, or
  your risk tolerance, and it has never seen one of your fills.</div>
</footer>

</div></body></html>""".format(
        tk=_esc(ticker), css=CSS, now=datetime.now(),
        px=("$" + _num(spot, 2)) if spot else "",
        dv=_esc(case.get("deep_verdict", "")),
        vcls=vcls, verdict=_esc(case["verdict"]), why=_esc(case["why"]),
        clock=_clock_html(clock),
        forc=_items_html(case["for"], "for"),
        against=_items_html(case["against"], "against"),
        unknown=unknown_block,
        structures=_structures_html(opt),
        cap="${:,.0f}".format(_cfg()["capital"]),
        maxpct="{:.0%}".format(_cfg()["max_position_pct"]),
        falsifiers=_falsifiers(case, opt),
        cn=cal.get("n", 0), cw=cal.get("winners", 0), cl=cal.get("losers", 0),
        ceff=cal.get("effective_n", "?"), pn=ps.get("n_episodes", 0),
        vn=(lp.get("vol_premium") or {}).get("n", 0))

    os.makedirs(OUT_DIR, exist_ok=True)
    path = out_path or os.path.join(
        OUT_DIR, "{}_{:%Y%m%d}.html".format(ticker.upper(), date.today()))
    with open(path, "w", encoding="utf-8") as f:
        f.write(doc)
    if open_after:
        try:
            webbrowser.open("file:///" + path.replace("\\", "/"))
        except Exception:
            pass
    return path
